apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats-streaming:0.17.0
          # hb - heart beat
          args: [
            '-p',
            '4222',
            '-m',
            '8222',
            # health checks
            # hbi - how often NATS is going to make a hb request to each of it's client
            '-hbi',
            '5s',
            # hbt - how long each client has to respond
            '-hbt',
            '5s',
            # hbf - number of times each client can fail before NATS assumes that the connection is dead and gone
            '-hbf',
            '2',
            '-SD',
            # cid - cluster ID
            '-cid',
            'ticketing'
          ]
---
apiVersion: v1
kind: Service
metadata:
  name: nats-srv
spec:
  selector:
    app: nats
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222
    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222
